// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG1ohHlXqdeQxF5S2gT0M4oPJCwUI8ADE',
    appId: '1:582080008358:web:ab9f0d5aba988bc0cd6467',
    messagingSenderId: '582080008358',
    projectId: 'klaras-koperasi',
    authDomain: 'klaras-koperasi.firebaseapp.com',
    storageBucket: 'klaras-koperasi.appspot.com',
    measurementId: 'G-EWLLSBWVRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvkyeya-JrXTR9U5B78UXwsPeYOuaHyTY',
    appId: '1:582080008358:android:1db4a874b415999fcd6467',
    messagingSenderId: '582080008358',
    projectId: 'klaras-koperasi',
    storageBucket: 'klaras-koperasi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJWYbe1nYzC8619hXrIJG6zeagRjJ8NZ4',
    appId: '1:582080008358:ios:8a0a62af3a5f6be4cd6467',
    messagingSenderId: '582080008358',
    projectId: 'klaras-koperasi',
    storageBucket: 'klaras-koperasi.appspot.com',
    iosClientId:
        '582080008358-ucccues0cevnq2nft1ei2mu2scec7nnc.apps.googleusercontent.com',
    iosBundleId: 'com.octastudio.koperasiKlaras',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJWYbe1nYzC8619hXrIJG6zeagRjJ8NZ4',
    appId: '1:582080008358:ios:8a0a62af3a5f6be4cd6467',
    messagingSenderId: '582080008358',
    projectId: 'klaras-koperasi',
    storageBucket: 'klaras-koperasi.appspot.com',
    iosClientId:
        '582080008358-ucccues0cevnq2nft1ei2mu2scec7nnc.apps.googleusercontent.com',
    iosBundleId: 'com.octastudio.koperasiKlaras',
  );
}
